### ISSUE TITLE
Items not considered for recipe tree in terminal

### ISSUE THREAD

**Issue by redstonekasi** [blocovermelho/ae2-emi-crafting#18]
When in a terminal, no items are considered for the recipe tree, not even in my inventory, when outside of a terminal it's fine. Any recipe when opening the recipe screen directly does work with "Fill Recipe". I am on 1.3.0 of the mod.

![20240303145443](https://github.com/blocovermelho/ae2-emi-crafting/assets/42352565/b5b053e9-97fb-4070-94e7-dd2b1965795a)

**Comment by roridev** [comment]
Can you check to see if this version fixes the issue? 
[ae2-emi-crafting-1.3.next.zip](https://github.com/blocovermelho/ae2-emi-crafting/files/14473436/ae2-emi-crafting-1.3.next.zip)

**Comment by redstonekasi** [comment]
This version does work somewhat, if the ingredients for a recipe are in the system, they're treated as existing in the synthetic favorites, but this does not work for the item itself, if the item is in my inventory, everything works fine now. I can confirm that the "Craftables" panel works for me as well.

**Comment by roridev** [comment]
I've reimplemented my old logic for handling with ME inventories on synthetic favourites.

Even though this should be considered a valid state, I have no idea on how to fix this since it would involve calling AppEng for every possible crafting recipe to know how many of them can be crafted with the items on the inventory. Imho its best that the bill of materials only shows items that *actually exist*. (In this image I have 3 wooden planks and thats why it shows "missing 5") instead of giving false positives with "possibly craftable" items.
  
![image](https://github.com/blocovermelho/ae2-emi-crafting/assets/36565196/e572fade-3f2d-4886-a646-ee93f3a90f69)
![image](https://github.com/blocovermelho/ae2-emi-crafting/assets/36565196/3deeaa9a-c509-43b2-a49f-1fc486d83356)

Can you see if that's what is the intended functionality you wanted?
[ae2-emi-crafting-1.3.next.zip](https://github.com/blocovermelho/ae2-emi-crafting/files/14473586/ae2-emi-crafting-1.3.next.zip)

**Comment by roridev** [comment]
So far I don't think items inside of the crafting inventory are accounted for, but that can easily be added.

This one is totally untested and i just added the code that *should* make that work, but no guarantees that it wont fabulously crash. 
[ae2-emi-crafting-1.3.next-crafting-grid.zip](https://github.com/blocovermelho/ae2-emi-crafting/files/14473659/ae2-emi-crafting-1.3.next-crafting-grid.zip)

**Comment by redstonekasi** [comment]
I've tested the version in your previous comment and it seems to work perfectly, I agree that anything that isn't actually in the system doesn't need to be displayed as available in the BoM.
There's two other problems I encountered while testing this: The behavior is only fixed in Crafting Terminals, normal Terminals still do not work correctly.
And I've encountered this crash, I wasn't able to get it again a second time:
<details>
```
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2024-03-03 17:04:34
Description: Rendering screen

java.lang.NullPointerException: The validated object is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:336)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:224)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at net.minecraft.class_2371.add(class_2371.java:59)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:336)
	at org.blocovermelho.ae2emicrafting.client.handler.generic.Ae2BaseRecipeHandler.getInventory(Ae2BaseRecipeHandler.java:58)
	at dev.emi.emi.api.recipe.EmiPlayerInventory.of(EmiPlayerInventory.java:84)
	at dev.emi.emi.screen.EmiScreenManager.updateCraftables(EmiScreenManager.java:233)
	at dev.emi.emi.screen.EmiScreenManager.recalculate(EmiScreenManager.java:133)
	at dev.emi.emi.screen.EmiScreenManager.drawBackground(EmiScreenManager.java:574)
	at net.minecraft.class_465.handler$cda000$emi$renderBackground(class_465.java:5217)
	at net.minecraft.class_465.method_25420(class_465.java:5208)
	at appeng.client.gui.AEBaseScreen.method_25394(AEBaseScreen.java:241)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Objects.requireNonNull(Objects.java:336)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:224)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at net.minecraft.class_2371.add(class_2371.java:59)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:336)
	at org.blocovermelho.ae2emicrafting.client.handler.generic.Ae2BaseRecipeHandler.getInventory(Ae2BaseRecipeHandler.java:58)
	at dev.emi.emi.api.recipe.EmiPlayerInventory.of(EmiPlayerInventory.java:84)
	at dev.emi.emi.screen.EmiScreenManager.updateCraftables(EmiScreenManager.java:233)
	at dev.emi.emi.screen.EmiScreenManager.recalculate(EmiScreenManager.java:133)
	at dev.emi.emi.screen.EmiScreenManager.drawBackground(EmiScreenManager.java:574)
	at net.minecraft.class_465.handler$cda000$emi$renderBackground(class_465.java:5217)
	at net.minecraft.class_465.method_25420(class_465.java:5208)
	at appeng.client.gui.AEBaseScreen.method_25394(AEBaseScreen.java:241)
	at net.minecraft.class_437.method_47413(class_437.java:110)

-- Screen render details --
Details:
	Screen name: appeng.client.gui.me.items.CraftingTermScreen
	Mouse location: Scaled: (480, 270). Absolute: (960.000000, 540.000000)
	Screen size: Scaled: (960, 540). Absolute: (3840, 2160). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 1 total; [class_746['redstonekasi'/2801099, l='ClientLevel', x=-1372.55, y=80.00, z=-675.81]]
	Chunk stats: 1024, 453 F: 6898 L: 0 U: 4225
	Level dimension: minecraft:overworld
	Level spawn location: World: (-80,70,144), Section: (at 0,6,0 in -5,4,9; chunk contains blocks -80,-64,144 to -65,319,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 31662325 game time, 36136825 day time
	Server brand: fabric (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
``` 
</details>

**Comment by redstonekasi** [comment]
> This one is totally untested and i just added the code that _should_ make that work, but no guarantees that it wont fabulously crash.
Tested this now and it works perfectly fine.

**Comment by redstonekasi** [comment]
Actually the crash from earlier *does* happen consistently.

**Comment by roridev** [comment]
> Actually the crash from earlier _does_ happen consistently upon opening any terminal.

I think i've seen that crash and fixed it, it shouldn't be happening on the later versions. Check to see if you dont have the mod installed twice.

**Comment by redstonekasi** [comment]
I've checked again to make sure, and it is indeed the correct version, this started happening in the 2nd build you sent me, normal 1.3.0 doesn't have this issue, neither does the first build you sent.

**Comment by roridev** [comment]
Maybe i forgot to run remapJar and sent the version *with* the crash. That could've happened. I'll do a clean build and send it here. 

Plain ME Storage Terminals should now also show the synthetic favourites and work on the BoM/Crafting Tree, but clicking the recipe does nothing and the quick craft button shows that you can't craft using them.

[ae2-emi-crafting-1.3.next-dev.zip](https://github.com/blocovermelho/ae2-emi-crafting/files/14473823/ae2-emi-crafting-1.3.next-dev.zip)

**Comment by redstonekasi** [comment]
The plain terminal does indeed work now, the crash however still happens.

**Comment by roridev** [comment]
Can you describe how you cause the crash?

**Comment by redstonekasi** [comment]
It just happens as soon as I open the terminal, I'm not doing anything else.

**Comment by roridev** [comment]
Send me your latest.log please, i need to check something

**Comment by redstonekasi** [comment]
https://mclo.gs/fzIW7q9

**Comment by roridev** [comment]
Okay... There might be something to this. I'll send a version which shouldn't crash but should give out errors if something interesting happening.
[ae2-emi-crafting-1.3.next-dev-debug.zip](https://github.com/blocovermelho/ae2-emi-crafting/files/14473934/ae2-emi-crafting-1.3.next-dev-debug.zip)

**Comment by redstonekasi** [comment]
```
[18:38:52] [Render thread/ERROR]: ================ Missing Converter Error =================
[18:38:52] [Render thread/ERROR]: :k GenericStack is class appeng.api.stacks.GenericStack
[18:38:52] [Render thread/ERROR]: Couldn't find a EmiStack converter for GenericStack: 1 WrappedGenericStack[wrapped_generic_stack]
[18:38:52] [Render thread/ERROR]: Please report this to the developers
[18:38:52] [Render thread/ERROR]: https://github.com/blocovermelho/ae2-emi-crafting
[18:38:52] [Render thread/ERROR]: ================ Missing Converter Error =================
```

**Comment by roridev** [comment]
yep that error is as descriptive as i imagined it would be, this one should actually show whats happening
[ae2-emi-crafting-2.0.0-dev.zip](https://github.com/blocovermelho/ae2-emi-crafting/files/14473970/ae2-emi-crafting-2.0.0-dev.zip)

**Comment by redstonekasi** [comment]
```
[18:51:49] [Render thread/ERROR]: ================ Missing Converter Error =================
[18:51:49] [Render thread/ERROR]: :k AeKey is class appbot.ae2.ManaKey
[18:51:49] [Render thread/ERROR]: Couldn't find a EmiStack converter for AeKey: {"#c":"appbot:mana"}
[18:51:49] [Render thread/ERROR]: Please report this to the developers
[18:51:49] [Render thread/ERROR]: https://github.com/blocovermelho/ae2-emi-crafting
[18:51:49] [Render thread/ERROR]: ================ Missing Converter Error =================
```
`appbot` is Applied Botanics, the relevant class is [here](https://github.com/ramidzkh/Applied-Botanics/blob/dev/1.20.1/common/src/main/java/appbot/ae2/ManaKey.java), in case that's important.

**Comment by roridev** [comment]
Yep. Thats a custom AeKey. This *now* makes sense of why I couldn't replicate your crash. 
This would be out of scope as long as the mod doesn't crash because of it. It'll enter as a new issue under Mod Compatibility or something.

**Comment by roridev** [comment]
This was made into a toggle-able feature which by default is turned off, changing that is easy since there is now a configuration screen on modmenu for the mod.
 
![image](https://github.com/blocovermelho/ae2-emi-crafting/assets/36565196/e034d0e6-a287-4da3-9ad9-a326a5c8e116)

**Comment by roridev** [comment]
Fixed
---
Dev: 4e770e7
MR: [1.3.1]()
CF: Pending
